### PR TITLE
French translation + README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds the French translation, corrects a mistake in the English one, and adds a button to get the app on F-Droid in the README.md

I assume your app is not on Google Play Store since I couldn't find it. If I'm wrong, tell me and I'll add the button to get the app on Google Play too ;)

If there are any new keys to translate in the future, you can ping me :)

Thanks for this app

### CODE REVIEW

**Comment by scheich** [comment]
Hi Poussinou,

merci beaucoup!

The app was on Play-Store, but I took it off after it was published on fdroid. Will increase version and it should be updated on fdroid in a few days.

Philipp

**Comment by scheich** [comment]
Hmm, fdroid not building, but the bot recognised the change:
https://gitlab.com/fdroid/fdroiddata/commit/29a641425095e6d8473fefa3878446b68f015191

**Comment by Poussinou** [comment]
Hum not sure why it doesn't build... Maybe you can open a request

**Comment by scheich** [comment]
Ok, tested compilation and uploaded apk, Works fine for me, So the build bot could do the same.I will wait another week and make a request.

**Pull request merged**
